version: '3.8'

services:
  app:
    container_name: project_app
    build:
      context: .
    env_file:
      - .env-non-dev
    ports:
      - 9999:8000
    depends_on:
      - db
    command:
      - '/fastapi_app/Docker/app.sh'


  db:
    image: postgres:16
    container_name: db_app
    env_file:
      - .env-non-dev