"""Add nickname column

Revision ID: d004901359cf
Revises: abd0bf040f1b
Create Date: 2024-10-02 00:29:32.288012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd004901359cf'
down_revision: Union[str, None] = 'abd0bf040f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('nickname', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat', 'nickname')
    # ### end Alembic commands ###
